service: manghe-api

provider:
  name: tencent
  runtime: Nodejs16.13
  region: ap-guangzhou

functions:
  manghe-api:
    handler: index.main_handler
    src: ./scf
    events:
      - http:
          parameters:
            netConfig:
              enableIntranet: true
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE
