export const SITE_PAGES = Object.freeze([
  {
    id: 'home',
    inputName: 'main',
    input: 'index.html',
    paths: ['', '/index.html'],
    title: '鲲鹏张导 · 项目入口',
    description: '鲲鹏张导项目站汇总入口，集中访问盲盒活动、名单展示、时光信箱与审核工作台。',
  },
  {
    id: 'blindboxVoting',
    inputName: 'blindbox',
    input: 'blindbox/index.html',
    paths: ['/blindbox', '/blindbox/index.html'],
    title: '十周年盲盒你来选 - 鲲鹏十周年盲盒排名工具',
    description: '十周年盲盒你来选 - 鲲鹏十周年盲盒稀有度排名工具，拖拽分配设备到传说、稀有、普通等级。',
  },
  {
    id: 'results',
    inputName: 'result',
    input: 'result/index.html',
    paths: ['/result', '/result/index.html'],
    title: '用户票选结果 - 十周年盲盒',
    description: '十周年盲盒用户票选结果：传说、稀有、普通三个等级的人气设备榜单。',
  },
  {
    id: 'activation',
    inputName: 'activate',
    input: 'activate/index.html',
    paths: ['/activate', '/activate/index.html'],
    title: '天火卡激活流程',
    description: '天火卡预约实名、开卡激活、购买流量及下单流程说明。',
  },
  {
    id: 'first50',
    inputName: 'first50',
    input: 'first50/index.html',
    paths: ['/first50', '/first50/index.html'],
    title: '天火卡首批 50 人名单',
    description: '天火卡首批 50 人入选名单。',
  },
  {
    id: 'thanks',
    inputName: 'thanks',
    input: 'thanks/index.html',
    paths: ['/thanks', '/thanks/index.html'],
    title: '鲲鹏张导感恩名单',
    description: '感谢每一位并肩同行、真诚支持鲲鹏张导的朋友。名单不分先后，真心同样珍贵。',
  },
  {
    id: 'voidBox',
    inputName: 'voidBox',
    input: 'void-box/index.html',
    paths: ['/void-box', '/void-box/index.html'],
    title: '虚空大帝盲盒名单',
    description: '虚空大帝盲盒 64 份订单登记名单，按订单时间排序。',
  },
  {
    id: 'mailbox',
    inputName: 'mail',
    input: 'mail/index.html',
    paths: ['/mail', '/mail/index.html'],
    title: '时光信箱｜把想说的话，一封封打开',
    description: '走进时光信箱，打开一格信箱，让写给不同人的信一封封呈现在眼前。',
  },
  {
    id: 'screening',
    inputName: 'screening',
    input: 'screening/index.html',
    paths: ['/screening', '/screening/index.html'],
    title: '天火卡｜直播筛选',
    description: '天火卡直播筛选页面，展示申请问答和原图并实时同步筛选结果。',
  },
  {
    id: 'screeningLightboard',
    inputName: 'screeningLightboard',
    input: 'screening/lightboard/index.html',
    paths: ['/screening/lightboard', '/screening/lightboard/index.html'],
    title: '天火卡｜灯牌审核',
    description: '天火卡灯牌专项审核页面，仅展示两张粉丝灯牌截图并同步灯牌总和。',
  },
  {
    id: 'eduScreening',
    inputName: 'eduScreening',
    input: 'edu-screening/index.html',
    paths: ['/edu-screening', '/edu-screening/index.html'],
    title: 'EDU 学生版｜申请审核台',
    description: 'EDU 学生版申请审核台，核验学生身份、真实需求与体验反馈意愿。',
  },
  {
    id: 'eduScreeningLive',
    inputName: 'eduScreeningLive',
    input: 'edu-screening/live/index.html',
    paths: ['/edu-screening/live', '/edu-screening/live/index.html'],
    title: 'EDU 学生版｜直播安全展示',
    description: 'EDU 学生版直播安全展示页，仅同步经过筛选的申请内容。',
  },
  {
    id: 'blindboxReview',
    inputName: 'blindboxReview',
    input: 'blindbox-review/index.html',
    paths: ['/blindbox-review', '/blindbox-review/index.html'],
    title: '盲盒置换审核｜中奖置换确认',
    description: '盲盒中奖置换审核页面，逐条审核用户置换请求。',
  },
])

export const VITE_INPUTS = Object.freeze(Object.fromEntries(
  SITE_PAGES.map(({ inputName, input }) => [inputName, input]),
))
